
CREATE TABLE category (
    category_id INT PRIMARY KEY,
    category_name VARCHAR(255) NOT NULL,
    category_groupname VARCHAR(255) NOT NULL
);

insert into

insert into category (category_id, category_name, category_groupname) VALUES
(1, 'Electronics', 'Technology'),
(2, 'Laptops', 'Technology'),
(3, 'Desktops', 'Technology'),
(4, 'Tablets', 'Technology'),
(5, 'Mobile Phones', 'Technology'),
(6, 'Wearable Technology', 'Technology'),
(7, 'Cameras', 'Technology'),
(8, 'Televisions', 'Technology'),
(9, 'Headphones', 'Technology'),
(10, 'Speakers', 'Technology'),
(11, 'Smart Home Devices', 'Technology'),
(12, 'Printers', 'Technology'),
(13, 'Computer Accessories', 'Technology'),
(14, 'Storage Devices', 'Technology'),
(15, 'Networking Devices', 'Technology'),
(16, 'Gaming Consoles', 'Technology'),
(17, 'Games', 'Technology'),
(18, 'Software', 'Technology'),
(19, 'Office Electronics', 'Technology'),
(20, 'Personal Care Electronics', 'Technology'),
(21, 'Home Appliances', 'Home'),
(22, 'Kitchen Appliances', 'Home'),
(23, 'Furniture', 'Home'),
(24, 'Bedding', 'Home'),
(25, 'Bath', 'Home'),
(26, 'Home Decor', 'Home'),
(27, 'Lighting', 'Home'),
(28, 'Storage Solutions', 'Home'),
(29, 'Cleaning Supplies', 'Home'),
(30, 'Tools', 'Home'),
(31, 'Gardening', 'Home'),
(32, 'Outdoor Furniture', 'Home'),
(33, 'Fitness Equipment', 'Sports'),
(34, 'Sports Gear', 'Sports'),
(35, 'Cycling', 'Sports'),
(36, 'Camping & Hiking', 'Sports'),
(37, 'Fishing', 'Sports'),
(38, 'Water Sports', 'Sports'),
(39, 'Winter Sports', 'Sports'),
(40, 'Team Sports', 'Sports'),
(41, 'Yoga', 'Sports'),
(42, 'Gymnastics', 'Sports'),
(43, 'Running', 'Sports'),
(44, 'Swimwear', 'Fashion'),
(45, 'Women''s Clothing', 'Fashion'),
(46, 'Men''s Clothing', 'Fashion'),
(47, 'Kids'' Clothing', 'Fashion'),
(48, 'Baby Clothing', 'Fashion'),
(49, 'Shoes', 'Fashion'),
(50, 'Bags & Accessories', 'Fashion'),
(51, 'Jewelry', 'Fashion'),
(52, 'Watches', 'Fashion'),
(53, 'Eyewear', 'Fashion'),
(54, 'Beauty Products', 'Beauty'),
(55, 'Skincare', 'Beauty'),
(56, 'Haircare', 'Beauty'),
(57, 'Makeup', 'Beauty'),
(58, 'Fragrances', 'Beauty'),
(59, 'Men''s Grooming', 'Beauty'),
(60, 'Health & Wellness', 'Beauty'),
(61, 'Vitamins & Supplements', 'Beauty'),
(62, 'Medical Supplies', 'Health'),
(63, 'Personal Care', 'Health'),
(64, 'Baby & Child Care', 'Health'),
(65, 'Elderly Care', 'Health'),
(66, 'Pet Supplies', 'Pets'),
(67, 'Pet Food', 'Pets'),
(68, 'Pet Toys', 'Pets'),
(69, 'Pet Grooming', 'Pets'),
(70, 'Pet Health', 'Pets'),
(71, 'Automotive', 'Automotive'),
(72, 'Car Electronics', 'Automotive'),
(73, 'Car Accessories', 'Automotive'),
(74, 'Car Care', 'Automotive'),
(75, 'Motorcycle Accessories', 'Automotive'),
(76, 'Tools & Equipment', 'Automotive'),
(77, 'Books', 'Books & Media'),
(78, 'Magazines', 'Books & Media'),
(79, 'Music', 'Books & Media'),
(80, 'Movies', 'Books & Media'),
(81, 'Video Games', 'Books & Media'),
(82, 'Board Games', 'Books & Media'),
(83, 'Toys', 'Toys & Games'),
(84, 'Dolls & Accessories', 'Toys & Games'),
(85, 'Action Figures', 'Toys & Games'),
(86, 'Building Sets', 'Toys & Games'),
(87, 'Educational Toys', 'Toys & Games'),
(88, 'Puzzles', 'Toys & Games'),
(89, 'Arts & Crafts', 'Toys & Games'),
(90, 'Party Supplies', 'Toys & Games'),
(91, 'Baking Supplies', 'Food & Beverage'),
(92, 'Pantry Staples', 'Food & Beverage'),
(93, 'Snacks', 'Food & Beverage'),
(94, 'Beverages', 'Food & Beverage'),
(95, 'Specialty Diet', 'Food & Beverage'),
(96, 'Fresh Produce', 'Food & Beverage'),
(97, 'Dairy & Eggs', 'Food & Beverage'),
(98, 'Meat & Seafood', 'Food & Beverage'),
(99, 'Frozen Foods', 'Food & Beverage'),
(100, 'Baking Supplies', 'Food & Beverage'),
(101, 'Wine & Spirits', 'Food & Beverage'),
(102, 'Travel Accessories', 'Travel'),
(103, 'Luggage', 'Travel'),
(104, 'Camping Gear', 'Travel'),
(105, 'Travel Clothing', 'Travel'),
(106, 'Travel Health', 'Travel'),
(107, 'Gift Cards', 'Gift'),
(108, 'Experiences', 'Gift'),
(109, 'Flowers', 'Gift'),
(110, 'Greeting Cards', 'Gift'),
(111, 'Party Supplies', 'Gift'),
(112, 'Electronics', 'Technology'),
(113, 'Laptops', 'Technology'),
(114, 'Desktops', 'Technology'),
(115, 'Tablets', 'Technology'),
(116, 'Mobile Phones', 'Technology'),
(117, 'Wearable Technology', 'Technology'),
(118, 'Cameras', 'Technology'),
(119, 'Televisions', 'Technology'),
(120, 'Headphones', 'Technology'),
(121, 'Speakers', 'Technology'),
(122, 'Smart Home Devices', 'Technology'),
(123, 'Printers', 'Technology'),
(124, 'Computer Accessories', 'Technology'),
(125, 'Storage Devices', 'Technology'),
(126, 'Networking Devices', 'Technology'),
(127, 'Gaming Consoles', 'Technology'),
(128, 'Games', 'Technology'),
(129, 'Software', 'Technology'),
(130, 'Office Electronics', 'Technology'),
(131, 'Personal Care Electronics', 'Technology'),
(132, 'Home Appliances', 'Home'),
(133, 'Kitchen Appliances', 'Home'),
(134, 'Furniture', 'Home'),
(135, 'Bedding', 'Home'),
(136, 'Bath', 'Home'),
(137, 'Home Decor', 'Home'),
(138, 'Lighting', 'Home'),
(139, 'Storage Solutions', 'Home'),
(140, 'Cleaning Supplies', 'Home'),
(141, 'Tools', 'Home'),
(142, 'Gardening', 'Home'),
(143, 'Outdoor Furniture', 'Home'),
(144, 'Fitness Equipment', 'Sports'),
(145, 'Sports Gear', 'Sports'),
(146, 'Cycling', 'Sports'),
(147, 'Camping & Hiking', 'Sports'),
(148, 'Fishing', 'Sports'),
(149, 'Water Sports', 'Sports'),
(150, 'Winter Sports', 'Sports'),
(151, 'Team Sports', 'Sports'),
(152, 'Yoga', 'Sports'),
(153, 'Gymnastics', 'Sports'),
(154, 'Running', 'Sports'),
(155, 'Swimwear', 'Fashion'),
(156, 'Women''s Clothing', 'Fashion'),
(157, 'Men''s Clothing', 'Fashion'),
(158, 'Kids'' Clothing', 'Fashion'),
(159, 'Baby Clothing', 'Fashion'),
(160, 'Shoes', 'Fashion'),
(161, 'Bags & Accessories', 'Fashion'),
(162, 'Jewelry', 'Fashion'),
(163, 'Watches', 'Fashion'),
(164, 'Eyewear', 'Fashion'),
(165, 'Beauty Products', 'Beauty'),
(166, 'Skincare', 'Beauty'),
(167, 'Haircare', 'Beauty'),
(168, 'Makeup', 'Beauty'),
(169, 'Fragrances', 'Beauty'),
(170, 'Men''s Grooming', 'Beauty'),
(171, 'Health & Wellness', 'Beauty'),
(172, 'Vitamins & Supplements', 'Beauty'),
(173, 'Medical Supplies', 'Health'),
(174, 'Personal Care', 'Health'),
(175, 'Baby & Child Care', 'Health'),
(176, 'Elderly Care', 'Health'),
(177, 'Pet Supplies', 'Pets'),
(178, 'Pet Food', 'Pets'),
(179, 'Pet Toys', 'Pets'),
(180, 'Pet Grooming', 'Pets'),
(181, 'Pet Health', 'Pets'),
(182, 'Automotive', 'Automotive'),
(183, 'Car Electronics', 'Automotive'),
(184, 'Car Accessories', 'Automotive'),
(185, 'Car Care', 'Automotive'),
(186, 'Motorcycle Accessories', 'Automotive'),
(187, 'Tools & Equipment', 'Automotive'),
(188, 'Books', 'Books & Media'),
(189, 'Magazines', 'Books & Media'),
(190, 'Music', 'Books & Media'),
(191, 'Movies', 'Books & Media'),
(192, 'Video Games', 'Books & Media'),
(193, 'Board Games', 'Books & Media'),
(194, 'Toys', 'Toys & Games'),
(195, 'Dolls & Accessories', 'Toys & Games'),
(196, 'Action Figures', 'Toys & Games'),
(197, 'Building Sets', 'Toys & Games'),
(198, 'Educational Toys', 'Toys & Games'),
(199, 'Puzzles', 'Toys & Games'),
(200, 'Arts & Crafts', 'Toys & Games'),
(201, 'Party Supplies', 'Toys & Games'),
(202, 'Baking Supplies', 'Food & Beverage'),
(203, 'Pantry Staples', 'Food & Beverage'),
(204, 'Snacks', 'Food & Beverage'),
(205, 'Beverages', 'Food & Beverage'),
(206, 'Specialty Diet', 'Food & Beverage'),
(207, 'Fresh Produce', 'Food & Beverage'),
(208, 'Dairy & Eggs', 'Food & Beverage'),
(209, 'Meat & Seafood', 'Food & Beverage'),
(210, 'Frozen Foods', 'Food & Beverage'),
(211, 'Baking Supplies', 'Food & Beverage'),
(212, 'Wine & Spirits', 'Food & Beverage'),
(213, 'Travel Accessories', 'Travel'),
(214, 'Luggage', 'Travel'),
(215, 'Camping Gear', 'Travel'),
(216, 'Travel Clothing', 'Travel'),
(217, 'Travel Health', 'Travel'),
(218, 'Gift Cards', 'Gift'),
(219, 'Experiences', 'Gift'),
(220, 'Flowers', 'Gift'),
(221, 'Greeting Cards', 'Gift'),
(222, 'Party Supplies', 'Gift'),
(223, 'Electronics', 'Technology'),
(224, 'Laptops', 'Technology'),
(225, 'Desktops', 'Technology'),
(226, 'Tablets', 'Technology'),
(227, 'Mobile Phones', 'Technology'),
(228, 'Wearable Technology', 'Technology'),
(229, 'Cameras', 'Technology'),
(230, 'Televisions', 'Technology'),
(231, 'Headphones', 'Technology'),
(232, 'Speakers', 'Technology'),
(233, 'Smart Home Devices', 'Technology'),
(234, 'Printers', 'Technology'),
(235, 'Computer Accessories', 'Technology'),
(236, 'Storage Devices', 'Technology'),
(237, 'Networking Devices', 'Technology'),
(238, 'Gaming Consoles', 'Technology'),
(239, 'Games', 'Technology'),
(240, 'Software', 'Technology'),
(241, 'Office Electronics', 'Technology'),
(242, 'Personal Care Electronics', 'Technology'),
(243, 'Home Appliances', 'Home'),
(244, 'Kitchen Appliances', 'Home'),
(245, 'Furniture', 'Home'),
(246, 'Bedding', 'Home'),
(247, 'Bath', 'Home'),
(248, 'Home Decor', 'Home'),
(249, 'Lighting', 'Home'),
(250, 'Storage Solutions', 'Home'),
(251, 'Cleaning Supplies', 'Home'),
(252, 'Tools', 'Home'),
(253, 'Gardening', 'Home'),
(254, 'Outdoor Furniture', 'Home'),
(255, 'Fitness Equipment', 'Sports'),
(256, 'Sports Gear', 'Sports'),
(257, 'Cycling', 'Sports'),
(258, 'Camping & Hiking', 'Sports'),
(259, 'Fishing', 'Sports'),
(260, 'Water Sports', 'Sports'),
(261, 'Winter Sports', 'Sports'),
(262, 'Team Sports', 'Sports'),
(263, 'Yoga', 'Sports'),
(264, 'Gymnastics', 'Sports'),
(265, 'Running', 'Sports'),
(266, 'Swimwear', 'Fashion'),
(267, 'Women''s Clothing', 'Fashion'),
(268, 'Men''s Clothing', 'Fashion'),
(269, 'Kids'' Clothing', 'Fashion'),
(270, 'Baby Clothing', 'Fashion'),
(271, 'Shoes', 'Fashion'),
(272, 'Bags & Accessories', 'Fashion'),
(273, 'Jewelry', 'Fashion'),
(274, 'Watches', 'Fashion'),
(275, 'Eyewear', 'Fashion'),
(276, 'Beauty Products', 'Beauty'),
(277, 'Skincare', 'Beauty'),
(278, 'Haircare', 'Beauty'),
(279, 'Makeup', 'Beauty'),
(280, 'Fragrances', 'Beauty'),
(281, 'Men''s Grooming', 'Beauty'),
(282, 'Health & Wellness', 'Beauty'),
(283, 'Vitamins & Supplements', 'Beauty'),
(284, 'Medical Supplies', 'Health'),
(285, 'Personal Care', 'Health'),
(286, 'Baby & Child Care', 'Health'),
(287, 'Elderly Care', 'Health'),
(288, 'Pet Supplies', 'Pets'),
(289, 'Pet Food', 'Pets'),
(290, 'Pet Toys', 'Pets'),
(291, 'Pet Grooming', 'Pets'),
(292, 'Pet Health', 'Pets'),
(293, 'Automotive', 'Automotive'),
(294, 'Car Electronics', 'Automotive'),
(295, 'Car Accessories', 'Automotive'),
(296, 'Car Care', 'Automotive'),
(297, 'Motorcycle Accessories', 'Automotive'),
(298, 'Tools & Equipment', 'Automotive'),
(299, 'Books', 'Books & Media'),
(300, 'Magazines', 'Books & Media'),
(301, 'Music', 'Books & Media'),
(302, 'Movies', 'Books & Media'),
(303, 'Video Games', 'Books & Media'),
(304, 'Board Games', 'Books & Media'),
(305, 'Toys', 'Toys & Games'),
(306, 'Dolls & Accessories', 'Toys & Games'),
(307, 'Action Figures', 'Toys & Games'),
(308, 'Building Sets', 'Toys & Games'),
(309, 'Educational Toys', 'Toys & Games'),
(310, 'Puzzles', 'Toys & Games'),
(311, 'Arts & Crafts', 'Toys & Games'),
(312, 'Party Supplies', 'Toys & Games'),
(313, 'Baking Supplies', 'Food & Beverage'),
(314, 'Pantry Staples', 'Food & Beverage'),
(315, 'Snacks', 'Food & Beverage'),
(316, 'Beverages', 'Food & Beverage'),
(317, 'Specialty Diet', 'Food & Beverage'),
(318, 'Fresh Produce', 'Food & Beverage'),
(319, 'Dairy & Eggs', 'Food & Beverage'),
(320, 'Meat & Seafood', 'Food & Beverage'),
(321, 'Frozen Foods', 'Food & Beverage'),
(322, 'Baking Supplies', 'Food & Beverage'),
(323, 'Wine & Spirits', 'Food & Beverage'),
(324, 'Travel Accessories', 'Travel'),
(325, 'Luggage', 'Travel'),
(326, 'Camping Gear', 'Travel'),
(327, 'Travel Clothing', 'Travel'),
(328, 'Travel Health', 'Travel'),
(329, 'Gift Cards', 'Gift'),
(330, 'Experiences', 'Gift'),
(331, 'Flowers', 'Gift'),
(332, 'Greeting Cards', 'Gift'),
(333, 'Party Supplies', 'Gift'),
(334, 'Electronics', 'Technology'),
(335, 'Laptops', 'Technology'),
(336, 'Desktops', 'Technology'),
(337, 'Tablets', 'Technology'),
(338, 'Mobile Phones', 'Technology'),
(339, 'Wearable Technology', 'Technology'),
(340, 'Cameras', 'Technology'),
(341, 'Televisions', 'Technology'),
(342, 'Headphones', 'Technology'),
(343, 'Speakers', 'Technology'),
(344, 'Smart Home Devices', 'Technology'),
(345, 'Printers', 'Technology'),
(346, 'Computer Accessories', 'Technology'),
(347, 'Storage Devices', 'Technology'),
(348, 'Networking Devices', 'Technology'),
(349, 'Gaming Consoles', 'Technology'),
(350, 'Games', 'Technology'),
(351, 'Software', 'Technology'),
(352, 'Office Electronics', 'Technology'),
(353, 'Personal Care Electronics', 'Technology'),
(354, 'Home Appliances', 'Home'),
(355, 'Kitchen Appliances', 'Home'),
(356, 'Furniture', 'Home'),
(357, 'Bedding', 'Home'),
(358, 'Bath', 'Home'),
(359, 'Home Decor', 'Home'),
(360, 'Lighting', 'Home'),
(361, 'Storage Solutions', 'Home'),
(362, 'Cleaning Supplies', 'Home'),
(363, 'Tools', 'Home'),
(364, 'Gardening', 'Home'),
(365, 'Outdoor Furniture', 'Home'),
(366, 'Fitness Equipment', 'Sports'),
(367, 'Sports Gear', 'Sports'),
(368, 'Cycling', 'Sports'),
(369, 'Camping & Hiking', 'Sports'),
(370, 'Fishing', 'Sports'),
(371, 'Water Sports', 'Sports'),
(372, 'Winter Sports', 'Sports'),
(373, 'Team Sports', 'Sports'),
(374, 'Yoga', 'Sports'),
(375, 'Gymnastics', 'Sports'),
(376, 'Running', 'Sports'),
(377, 'Swimwear', 'Fashion'),
(378, 'Women''s Clothing', 'Fashion'),
(379, 'Men''s Clothing', 'Fashion'),
(380, 'Kids'' Clothing', 'Fashion'),
(381, 'Baby Clothing', 'Fashion'),
(382, 'Shoes', 'Fashion'),
(383, 'Bags & Accessories', 'Fashion'),
(384, 'Jewelry', 'Fashion'),
(385, 'Watches', 'Fashion'),
(386, 'Eyewear', 'Fashion'),
(387, 'Beauty Products', 'Beauty'),
(388, 'Skincare', 'Beauty'),
(389, 'Haircare', 'Beauty'),
(390, 'Makeup', 'Beauty'),
(391, 'Fragrances', 'Beauty'),
(392, 'Men''s Grooming', 'Beauty'),
(393, 'Health & Wellness', 'Beauty'),
(394, 'Vitamins & Supplements', 'Beauty'),
(395, 'Medical Supplies', 'Health'),
(396, 'Personal Care', 'Health'),
(397, 'Baby & Child Care', 'Health'),
(398, 'Elderly Care', 'Health'),
(399, 'Pet Supplies', 'Pets'),
(400, 'Pet Food', 'Pets'),
(401, 'Pet Toys', 'Pets'),
(402, 'Pet Grooming', 'Pets'),
(403, 'Pet Health', 'Pets'),
(404, 'Automotive', 'Automotive'),
(405, 'Car Electronics', 'Automotive'),
(406, 'Car Accessories', 'Automotive'),
(407, 'Car Care', 'Automotive'),
(408, 'Motorcycle Accessories', 'Automotive'),
(409, 'Tools & Equipment', 'Automotive'),
(410, 'Books', 'Books & Media'),
(411, 'Magazines', 'Books & Media'),
(412, 'Music', 'Books & Media'),
(413, 'Movies', 'Books & Media'),
(414, 'Video Games', 'Books & Media'),
(415, 'Board Games', 'Books & Media'),
(416, 'Toys', 'Toys & Games'),
(417, 'Dolls & Accessories', 'Toys & Games'),
(418, 'Action Figures', 'Toys & Games'),
(419, 'Building Sets', 'Toys & Games'),
(420, 'Educational Toys', 'Toys & Games'),
(421, 'Puzzles', 'Toys & Games'),
(422, 'Arts & Crafts', 'Toys & Games'),
(423, 'Party Supplies', 'Toys & Games'),
(424, 'Baking Supplies', 'Food & Beverage'),
(425, 'Pantry Staples', 'Food & Beverage'),
(426, 'Snacks', 'Food & Beverage'),
(427, 'Beverages', 'Food & Beverage'),
(428, 'Specialty Diet', 'Food & Beverage'),
(429, 'Fresh Produce', 'Food & Beverage'),
(430, 'Dairy & Eggs', 'Food & Beverage'),
(431, 'Meat & Seafood', 'Food & Beverage'),
(432, 'Frozen Foods', 'Food & Beverage'),
(433, 'Baking Supplies', 'Food & Beverage'),
(434, 'Wine & Spirits', 'Food & Beverage'),
(435, 'Travel Accessories', 'Travel'),
(436, 'Luggage', 'Travel'),
(437, 'Camping Gear', 'Travel'),
(438, 'Travel Clothing', 'Travel'),
(439, 'Travel Health', 'Travel'),
(440, 'Gift Cards', 'Gift'),
(441, 'Experiences', 'Gift'),
(442, 'Flowers', 'Gift'),
(443, 'Greeting Cards', 'Gift'),
(444, 'Party Supplies', 'Gift'),
(445, 'Electronics', 'Technology'),
(446, 'Laptops', 'Technology'),
(447, 'Desktops', 'Technology'),
(448, 'Tablets', 'Technology'),
(449, 'Mobile Phones', 'Technology'),
(450, 'Wearable Technology', 'Technology'),
(451, 'Cameras', 'Technology'),
(452, 'Televisions', 'Technology'),
(453, 'Headphones', 'Technology'),
(454, 'Speakers', 'Technology'),
(455, 'Smart Home Devices', 'Technology'),
(456, 'Printers', 'Technology'),
(457, 'Computer Accessories', 'Technology'),
(458, 'Storage Devices', 'Technology'),
(459, 'Networking Devices', 'Technology'),
(460, 'Gaming Consoles', 'Technology'),
(461, 'Games', 'Technology'),
(462, 'Software', 'Technology'),
(463, 'Office Electronics', 'Technology'),
(464, 'Personal Care Electronics', 'Technology'),
(465, 'Home Appliances', 'Home'),
(466, 'Kitchen Appliances', 'Home'),
(467, 'Furniture', 'Home'),
(468, 'Bedding', 'Home'),
(469, 'Bath', 'Home'),
(470, 'Home Decor', 'Home'),
(471, 'Lighting', 'Home'),
(472, 'Storage Solutions', 'Home'),
(473, 'Cleaning Supplies', 'Home'),
(474, 'Tools', 'Home'),
(475, 'Gardening', 'Home'),
(476, 'Outdoor Furniture', 'Home'),
(477, 'Fitness Equipment', 'Sports'),
(478, 'Sports Gear', 'Sports'),
(479, 'Cycling', 'Sports'),
(480, 'Camping & Hiking', 'Sports'),
(481, 'Fishing', 'Sports'),
(482, 'Water Sports', 'Sports'),
(483, 'Winter Sports', 'Sports'),
(484, 'Team Sports', 'Sports'),
(485, 'Yoga', 'Sports'),
(486, 'Gymnastics', 'Sports'),
(487, 'Running', 'Sports'),
(488, 'Swimwear', 'Fashion'),
(489, 'Women''s Clothing', 'Fashion'),
(490, 'Men''s Clothing', 'Fashion'),
(491, 'Kids'' Clothing', 'Fashion'),
(492, 'Baby Clothing', 'Fashion'),
(493, 'Shoes', 'Fashion'),
(494, 'Bags & Accessories', 'Fashion'),
(495, 'Jewelry', 'Fashion'),
(496, 'Watches', 'Fashion'),
(497, 'Eyewear', 'Fashion'),
(498, 'Beauty Products', 'Beauty'),
(499, 'Skincare', 'Beauty'),
(500, 'Haircare', 'Beauty'),
(501, 'Makeup', 'Beauty'),
(502, 'Fragrances', 'Beauty'),
(503, 'Men''s Grooming', 'Beauty'),
(504, 'Health & Wellness', 'Beauty'),
(505, 'Vitamins & Supplements', 'Beauty'),
(506, 'Medical Supplies', 'Health'),
(507, 'Personal Care', 'Health'),
(508, 'Baby & Child Care', 'Health'),
(509, 'Elderly Care', 'Health'),
(510, 'Pet Supplies', 'Pets'),
(511, 'Pet Food', 'Pets'),
(512, 'Pet Toys', 'Pets'),
(513, 'Pet Grooming', 'Pets'),
(514, 'Pet Health', 'Pets'),
(515, 'Automotive', 'Automotive'),
(516, 'Car Electronics', 'Automotive'),
(517, 'Car Accessories', 'Automotive'),
(518, 'Car Care', 'Automotive'),
(519, 'Motorcycle Accessories', 'Automotive'),
(520, 'Tools & Equipment', 'Automotive'),
(521, 'Books', 'Books & Media'),
(522, 'Magazines', 'Books & Media'),
(523, 'Music', 'Books & Media'),
(524, 'Movies', 'Books & Media'),
(525, 'Video Games', 'Books & Media'),
(526, 'Board Games', 'Books & Media'),
(527, 'Toys', 'Toys & Games'),
(528, 'Dolls & Accessories', 'Toys & Games'),
(529, 'Action Figures', 'Toys & Games'),
(530, 'Building Sets', 'Toys & Games'),
(531, 'Educational Toys', 'Toys & Games'),
(532, 'Puzzles', 'Toys & Games'),
(533, 'Arts & Crafts', 'Toys & Games'),
(534, 'Party Supplies', 'Toys & Games'),
(535, 'Baking Supplies', 'Food & Beverage'),
(536, 'Pantry Staples', 'Food & Beverage'),
(537, 'Snacks', 'Food & Beverage'),
(538, 'Beverages', 'Food & Beverage'),
(539, 'Specialty Diet', 'Food & Beverage'),
(540, 'Fresh Produce', 'Food & Beverage'),
(541, 'Dairy & Eggs', 'Food & Beverage'),
(542, 'Meat & Seafood', 'Food & Beverage'),
(543, 'Frozen Foods', 'Food & Beverage'),
(544, 'Baking Supplies', 'Food & Beverage'),
(545, 'Wine & Spirits', 'Food & Beverage'),
(546, 'Travel Accessories', 'Travel'),
(547, 'Luggage', 'Travel'),
(548, 'Camping Gear', 'Travel'),
(549, 'Travel Clothing', 'Travel'),
(550, 'Travel Health', 'Travel'),
(551, 'Gift Cards', 'Gift'),
(552, 'Experiences', 'Gift'),
(553, 'Flowers', 'Gift'),
(554, 'Greeting Cards', 'Gift'),
(555, 'Party Supplies', 'Gift'),
(556, 'Electronics', 'Technology'),
(557, 'Laptops', 'Technology'),
(558, 'Desktops', 'Technology'),
(559, 'Tablets', 'Technology'),
(560, 'Mobile Phones', 'Technology'),
(561, 'Wearable Technology', 'Technology'),
(562, 'Cameras', 'Technology'),
(563, 'Televisions', 'Technology'),
(564, 'Headphones', 'Technology'),
(565, 'Speakers', 'Technology'),
(566, 'Smart Home Devices', 'Technology'),
(567, 'Printers', 'Technology'),
(568, 'Computer Accessories', 'Technology'),
(569, 'Storage Devices', 'Technology'),
(570, 'Networking Devices', 'Technology'),
(571, 'Gaming Consoles', 'Technology'),
(572, 'Games', 'Technology'),
(573, 'Software', 'Technology'),
(574, 'Office Electronics', 'Technology'),
(575, 'Personal Care Electronics', 'Technology'),
(576, 'Home Appliances', 'Home'),
(577, 'Kitchen Appliances', 'Home'),
(578, 'Furniture', 'Home'),
(579, 'Bedding', 'Home'),
(580, 'Bath', 'Home'),
(581, 'Home Decor', 'Home'),
(582, 'Lighting', 'Home'),
(583, 'Storage Solutions', 'Home'),
(584, 'Cleaning Supplies', 'Home'),
(585, 'Tools', 'Home'),
(586, 'Gardening', 'Home'),
(587, 'Outdoor Furniture', 'Home'),
(588, 'Fitness Equipment', 'Sports'),
(589, 'Sports Gear', 'Sports'),
(590, 'Cycling', 'Sports'),
(591, 'Camping & Hiking', 'Sports'),
(592, 'Fishing', 'Sports'),
(593, 'Water Sports', 'Sports'),
(594, 'Winter Sports', 'Sports'),
(595, 'Team Sports', 'Sports'),
(596, 'Yoga', 'Sports'),
(597, 'Gymnastics', 'Sports'),
(598, 'Running', 'Sports'),
(599, 'Swimwear', 'Fashion'),
(600, 'Women''s Clothing', 'Fashion'),
(601, 'Men''s Clothing', 'Fashion'),
(602, 'Kids'' Clothing', 'Fashion'),
(603, 'Baby Clothing', 'Fashion'),
(604, 'Shoes', 'Fashion'),
(605, 'Bags & Accessories', 'Fashion'),
(606, 'Jewelry', 'Fashion'),
(607, 'Watches', 'Fashion'),
(608, 'Eyewear', 'Fashion'),
(609, 'Beauty Products', 'Beauty'),
(610, 'Skincare', 'Beauty'),
(611, 'Haircare', 'Beauty'),
(612, 'Makeup', 'Beauty'),
(613, 'Fragrances', 'Beauty'),
(614, 'Men''s Grooming', 'Beauty'),
(615, 'Health & Wellness', 'Beauty'),
(616, 'Vitamins & Supplements', 'Beauty'),
(617, 'Medical Supplies', 'Health'),
(618, 'Personal Care', 'Health'),
(619, 'Baby & Child Care', 'Health'),
(620, 'Elderly Care', 'Health'),
(621, 'Pet Supplies', 'Pets'),
(622, 'Pet Food', 'Pets'),
(623, 'Pet Toys', 'Pets'),
(624, 'Pet Grooming', 'Pets'),
(625, 'Pet Health', 'Pets'),
(626, 'Automotive', 'Automotive'),
(627, 'Car Electronics', 'Automotive'),
(628, 'Car Accessories', 'Automotive'),
(629, 'Car Care', 'Automotive'),
(630, 'Motorcycle Accessories', 'Automotive'),
(631, 'Tools & Equipment', 'Automotive'),
(632, 'Books', 'Books & Media'),
(633, 'Magazines', 'Books & Media'),
(634, 'Music', 'Books & Media'),
(635, 'Movies', 'Books & Media'),
(636, 'Video Games', 'Books & Media'),
(637, 'Board Games', 'Books & Media'),
(638, 'Toys', 'Toys & Games'),
(639, 'Dolls & Accessories', 'Toys & Games'),
(640, 'Action Figures', 'Toys & Games'),
(641, 'Building Sets', 'Toys & Games'),
(642, 'Educational Toys', 'Toys & Games'),
(643, 'Puzzles', 'Toys & Games'),
(644, 'Arts & Crafts', 'Toys & Games'),
(645, 'Party Supplies', 'Toys & Games'),
(646, 'Baking Supplies', 'Food & Beverage'),
(647, 'Pantry Staples', 'Food & Beverage'),
(648, 'Snacks', 'Food & Beverage'),
(649, 'Beverages', 'Food & Beverage'),
(650, 'Specialty Diet', 'Food & Beverage'),
(651, 'Fresh Produce', 'Food & Beverage'),
(652, 'Dairy & Eggs', 'Food & Beverage'),
(653, 'Meat & Seafood', 'Food & Beverage'),
(654, 'Frozen Foods', 'Food & Beverage'),
(655, 'Baking Supplies', 'Food & Beverage'),
(656, 'Wine & Spirits', 'Food & Beverage'),
(657, 'Travel Accessories', 'Travel'),
(658, 'Luggage', 'Travel'),
(659, 'Camping Gear', 'Travel'),
(660, 'Travel Clothing', 'Travel'),
(661, 'Travel Health', 'Travel'),
(662, 'Gift Cards', 'Gift'),
(663, 'Experiences', 'Gift'),
(664, 'Flowers', 'Gift'),
(665, 'Greeting Cards', 'Gift'),
(666, 'Party Supplies', 'Gift'),
(667, 'Electronics', 'Technology'),
(668, 'Laptops', 'Technology'),
(669, 'Desktops', 'Technology'),
(670, 'Tablets', 'Technology'),
(671, 'Mobile Phones', 'Technology'),
(672, 'Wearable Technology', 'Technology'),
(673, 'Cameras', 'Technology'),
(674, 'Televisions', 'Technology'),
(675, 'Headphones', 'Technology'),
(676, 'Speakers', 'Technology'),
(677, 'Smart Home Devices', 'Technology'),
(678, 'Printers', 'Technology'),
(679, 'Computer Accessories', 'Technology'),
(680, 'Storage Devices', 'Technology'),
(681, 'Networking Devices', 'Technology'),
(682, 'Gaming Consoles', 'Technology'),
(683, 'Games', 'Technology'),
(684, 'Software', 'Technology'),
(685, 'Office Electronics', 'Technology'),
(686, 'Personal Care Electronics', 'Technology'),
(687, 'Home Appliances', 'Home'),
(688, 'Kitchen Appliances', 'Home'),
(689, 'Furniture', 'Home'),
(690, 'Bedding', 'Home'),
(691, 'Bath', 'Home'),
(692, 'Home Decor', 'Home'),
(693, 'Lighting', 'Home'),
(694, 'Storage Solutions', 'Home'),
(695, 'Cleaning Supplies', 'Home'),
(696, 'Tools', 'Home'),
(697, 'Gardening', 'Home'),
(698, 'Outdoor Furniture', 'Home'),
(699, 'Fitness Equipment', 'Sports'),
(700, 'Sports Gear', 'Sports'),
(701, 'Cycling', 'Sports'),
(702, 'Camping & Hiking', 'Sports'),
(703, 'Fishing', 'Sports'),
(704, 'Water Sports', 'Sports'),
(705, 'Winter Sports', 'Sports'),
(706, 'Team Sports', 'Sports'),
(707, 'Yoga', 'Sports'),
(708, 'Gymnastics', 'Sports'),
(709, 'Running', 'Sports'),
(710, 'Swimwear', 'Fashion'),
(711, 'Women''s Clothing', 'Fashion'),
(712, 'Men''s Clothing', 'Fashion'),
(713, 'Kids'' Clothing', 'Fashion'),
(714, 'Baby Clothing', 'Fashion'),
(715, 'Shoes', 'Fashion'),
(716, 'Bags & Accessories', 'Fashion'),
(717, 'Jewelry', 'Fashion'),
(718, 'Watches', 'Fashion'),
(719, 'Eyewear', 'Fashion'),
(720, 'Beauty Products', 'Beauty'),
(721, 'Skincare', 'Beauty'),
(722, 'Haircare', 'Beauty'),
(723, 'Makeup', 'Beauty'),
(724, 'Fragrances', 'Beauty'),
(725, 'Men''s Grooming', 'Beauty'),
(726, 'Health & Wellness', 'Beauty'),
(727, 'Vitamins & Supplements', 'Beauty'),
(728, 'Medical Supplies', 'Health'),
(729, 'Personal Care', 'Health'),
(730, 'Baby & Child Care', 'Health'),
(731, 'Elderly Care', 'Health'),
(732, 'Pet Supplies', 'Pets'),
(733, 'Pet Food', 'Pets'),
(734, 'Pet Toys', 'Pets'),
(735, 'Pet Grooming', 'Pets'),
(736, 'Pet Health', 'Pets'),
(737, 'Automotive', 'Automotive'),
(738, 'Car Electronics', 'Automotive'),
(739, 'Car Accessories', 'Automotive'),
(740, 'Car Care', 'Automotive'),
(741, 'Motorcycle Accessories', 'Automotive'),
(742, 'Tools & Equipment', 'Automotive'),
(743, 'Books', 'Books & Media'),
(744, 'Magazines', 'Books & Media'),
(745, 'Music', 'Books & Media'),
(746, 'Movies', 'Books & Media'),
(747, 'Video Games', 'Books & Media'),
(748, 'Board Games', 'Books & Media'),
(749, 'Toys', 'Toys & Games'),
(750, 'Dolls & Accessories', 'Toys & Games'),
(751, 'Action Figures', 'Toys & Games'),
(752, 'Building Sets', 'Toys & Games'),
(753, 'Educational Toys', 'Toys & Games'),
(754, 'Puzzles', 'Toys & Games'),
(755, 'Arts & Crafts', 'Toys & Games'),
(756, 'Party Supplies', 'Toys & Games'),
(757, 'Baking Supplies', 'Food & Beverage'),
(758, 'Pantry Staples', 'Food & Beverage'),
(759, 'Snacks', 'Food & Beverage'),
(760, 'Beverages', 'Food & Beverage'),
(761, 'Specialty Diet', 'Food & Beverage'),
(762, 'Fresh Produce', 'Food & Beverage'),
(763, 'Dairy & Eggs', 'Food & Beverage'),
(764, 'Meat & Seafood', 'Food & Beverage'),
(765, 'Frozen Foods', 'Food & Beverage'),
(766, 'Baking Supplies', 'Food & Beverage'),
(767, 'Wine & Spirits', 'Food & Beverage'),
(768, 'Travel Accessories', 'Travel'),
(769, 'Luggage', 'Travel'),
(770, 'Camping Gear', 'Travel'),
(771, 'Travel Clothing', 'Travel'),
(772, 'Travel Health', 'Travel'),
(773, 'Gift Cards', 'Gift'),
(774, 'Experiences', 'Gift'),
(775, 'Flowers', 'Gift'),
(776, 'Greeting Cards', 'Gift'),
(777, 'Party Supplies', 'Gift'),
(778, 'Electronics', 'Technology'),
(779, 'Laptops', 'Technology'),
(780, 'Desktops', 'Technology'),
(781, 'Tablets', 'Technology'),
(782, 'Mobile Phones', 'Technology'),
(783, 'Wearable Technology', 'Technology'),
(784, 'Cameras', 'Technology'),
(785, 'Televisions', 'Technology'),
(786, 'Headphones', 'Technology'),
(787, 'Speakers', 'Technology'),
(788, 'Smart Home Devices', 'Technology'),
(789, 'Printers', 'Technology'),
(790, 'Computer Accessories', 'Technology'),
(791, 'Storage Devices', 'Technology'),
(792, 'Networking Devices', 'Technology'),
(793, 'Gaming Consoles', 'Technology'),
(794, 'Games', 'Technology'),
(795, 'Software', 'Technology'),
(796, 'Office Electronics', 'Technology'),
(797, 'Personal Care Electronics', 'Technology'),
(798, 'Home Appliances', 'Home'),
(799, 'Kitchen Appliances', 'Home'),
(800, 'Furniture', 'Home'),
(801, 'Bedding', 'Home'),
(802, 'Bath', 'Home'),
(803, 'Home Decor', 'Home'),
(804, 'Lighting', 'Home'),
(805, 'Storage Solutions', 'Home'),
(806, 'Cleaning Supplies', 'Home'),
(807, 'Tools', 'Home'),
(808, 'Gardening', 'Home'),
(809, 'Outdoor Furniture', 'Home'),
(810, 'Fitness Equipment', 'Sports'),
(811, 'Sports Gear', 'Sports'),
(812, 'Cycling', 'Sports'),
(813, 'Camping & Hiking', 'Sports'),
(814, 'Fishing', 'Sports'),
(815, 'Water Sports', 'Sports'),
(816, 'Winter Sports', 'Sports'),
(817, 'Team Sports', 'Sports'),
(818, 'Yoga', 'Sports'),
(819, 'Gymnastics', 'Sports'),
(820, 'Running', 'Sports'),
(821, 'Swimwear', 'Fashion'),
(822, 'Women''s Clothing', 'Fashion'),
(823, 'Men''s Clothing', 'Fashion'),
(824, 'Kids'' Clothing', 'Fashion'),
(825, 'Baby Clothing', 'Fashion'),
(826, 'Shoes', 'Fashion'),
(827, 'Bags & Accessories', 'Fashion'),
(828, 'Jewelry', 'Fashion'),
(829, 'Watches', 'Fashion'),
(830, 'Eyewear', 'Fashion'),
(831, 'Beauty Products', 'Beauty'),
(832, 'Skincare', 'Beauty'),
(833, 'Haircare', 'Beauty'),
(834, 'Makeup', 'Beauty'),
(835, 'Fragrances', 'Beauty'),
(836, 'Men''s Grooming', 'Beauty'),
(837, 'Health & Wellness', 'Beauty'),
(838, 'Vitamins & Supplements', 'Beauty'),
(839, 'Medical Supplies', 'Health'),
(840, 'Personal Care', 'Health'),
(841, 'Baby & Child Care', 'Health'),
(842, 'Elderly Care', 'Health'),
(843, 'Pet Supplies', 'Pets'),
(844, 'Pet Food', 'Pets'),
(845, 'Pet Toys', 'Pets'),
(846, 'Pet Grooming', 'Pets'),
(847, 'Pet Health', 'Pets'),
(848, 'Automotive', 'Automotive'),
(849, 'Car Electronics', 'Automotive'),
(850, 'Car Accessories', 'Automotive'),
(851, 'Car Care', 'Automotive'),
(852, 'Motorcycle Accessories', 'Automotive'),
(853, 'Tools & Equipment', 'Automotive'),
(854, 'Books', 'Books & Media'),
(855, 'Magazines', 'Books & Media'),
(856, 'Music', 'Books & Media'),
(857, 'Movies', 'Books & Media'),
(858, 'Video Games', 'Books & Media'),
(859, 'Board Games', 'Books & Media'),
(860, 'Toys', 'Toys & Games'),
(861, 'Dolls & Accessories', 'Toys & Games'),
(862, 'Action Figures', 'Toys & Games'),
(863, 'Building Sets', 'Toys & Games'),
(864, 'Educational Toys', 'Toys & Games'),
(865, 'Puzzles', 'Toys & Games'),
(866, 'Arts & Crafts', 'Toys & Games'),
(867, 'Party Supplies', 'Toys & Games'),
(868, 'Baking Supplies', 'Food & Beverage'),
(869, 'Pantry Staples', 'Food & Beverage'),
(870, 'Snacks', 'Food & Beverage'),
(871, 'Beverages', 'Food & Beverage'),
(872, 'Specialty Diet', 'Food & Beverage'),
(873, 'Fresh Produce', 'Food & Beverage'),
(874, 'Dairy & Eggs', 'Food & Beverage'),
(875, 'Meat & Seafood', 'Food & Beverage'),
(876, 'Frozen Foods', 'Food & Beverage'),
(877, 'Baking Supplies', 'Food & Beverage'),
(878, 'Wine & Spirits', 'Food & Beverage'),
(879, 'Travel Accessories', 'Travel'),
(880, 'Luggage', 'Travel'),
(881, 'Camping Gear', 'Travel'),
(882, 'Travel Clothing', 'Travel'),
(883, 'Travel Health', 'Travel'),
(884, 'Gift Cards', 'Gift'),
(885, 'Experiences', 'Gift'),
(886, 'Flowers', 'Gift'),
(887, 'Greeting Cards', 'Gift'),
(888, 'Party Supplies', 'Gift'),
(889, 'Electronics', 'Technology'),
(890, 'Laptops', 'Technology'),
(891, 'Desktops', 'Technology'),
(892, 'Tablets', 'Technology'),
(893, 'Mobile Phones', 'Technology'),
(894, 'Wearable Technology', 'Technology'),
(895, 'Cameras', 'Technology'),
(896, 'Televisions', 'Technology'),
(897, 'Headphones', 'Technology'),
(898, 'Speakers', 'Technology'),
(899, 'Smart Home Devices', 'Technology'),
(900, 'Printers', 'Technology'),
(901, 'Computer Accessories', 'Technology'),
(902, 'Storage Devices', 'Technology'),
(903, 'Networking Devices', 'Technology'),
(904, 'Gaming Consoles', 'Technology'),
(905, 'Games', 'Technology'),
(906, 'Software', 'Technology'),
(907, 'Office Electronics', 'Technology'),
(908, 'Personal Care Electronics', 'Technology'),
(909, 'Home Appliances', 'Home'),
(910, 'Kitchen Appliances', 'Home'),
(911, 'Furniture', 'Home'),
(912, 'Bedding', 'Home'),
(913, 'Bath', 'Home'),
(914, 'Home Decor', 'Home'),
(915, 'Lighting', 'Home'),
(916, 'Storage Solutions', 'Home'),
(917, 'Cleaning Supplies', 'Home'),
(918, 'Tools', 'Home'),
(919, 'Gardening', 'Home'),
(920, 'Outdoor Furniture', 'Home'),
(921, 'Fitness Equipment', 'Sports'),
(922, 'Sports Gear', 'Sports'),
(923, 'Cycling', 'Sports'),
(924, 'Camping & Hiking', 'Sports'),
(925, 'Fishing', 'Sports'),
(926, 'Water Sports', 'Sports'),
(927, 'Winter Sports', 'Sports'),
(928, 'Team Sports', 'Sports'),
(929, 'Yoga', 'Sports'),
(930, 'Gymnastics', 'Sports'),
(931, 'Running', 'Sports'),
(932, 'Swimwear', 'Fashion'),
(933, 'Women''s Clothing', 'Fashion'),
(934, 'Men''s Clothing', 'Fashion'),
(935, 'Kids'' Clothing', 'Fashion'),
(936, 'Baby Clothing', 'Fashion'),
(937, 'Shoes', 'Fashion'),
(938, 'Bags & Accessories', 'Fashion'),
(939, 'Jewelry', 'Fashion'),
(940, 'Watches', 'Fashion'),
(941, 'Eyewear', 'Fashion'),
(942, 'Beauty Products', 'Beauty'),
(943, 'Skincare', 'Beauty'),
(944, 'Haircare', 'Beauty'),
(945, 'Makeup', 'Beauty'),
(946, 'Fragrances', 'Beauty'),
(947, 'Men''s Grooming', 'Beauty'),
(948, 'Health & Wellness', 'Beauty'),
(949, 'Vitamins & Supplements', 'Beauty'),
(950, 'Medical Supplies', 'Health'),
(951, 'Personal Care', 'Health'),
(952, 'Baby & Child Care', 'Health'),
(953, 'Elderly Care', 'Health'),
(954, 'Pet Supplies', 'Pets'),
(955, 'Pet Food', 'Pets'),
(956, 'Pet Toys', 'Pets'),
(957, 'Pet Grooming', 'Pets'),
(958, 'Pet Health', 'Pets'),
(959, 'Automotive', 'Automotive'),
(960, 'Car Electronics', 'Automotive'),
(961, 'Car Accessories', 'Automotive'),
(962, 'Car Care', 'Automotive'),
(963, 'Motorcycle Accessories', 'Automotive'),
(964, 'Tools & Equipment', 'Automotive'),
(965, 'Books', 'Books & Media'),
(966, 'Magazines', 'Books & Media'),
(967, 'Music', 'Books & Media'),
(968, 'Movies', 'Books & Media'),
(969, 'Video Games', 'Books & Media'),
(970, 'Board Games', 'Books & Media'),
(971, 'Toys', 'Toys & Games'),
(972, 'Dolls & Accessories', 'Toys & Games'),
(973, 'Action Figures', 'Toys & Games'),
(974, 'Building Sets', 'Toys & Games'),
(975, 'Educational Toys', 'Toys & Games'),
(976, 'Puzzles', 'Toys & Games'),
(977, 'Arts & Crafts', 'Toys & Games'),
(978, 'Party Supplies', 'Toys & Games'),
(979, 'Baking Supplies', 'Food & Beverage'),
(980, 'Pantry Staples', 'Food & Beverage'),
(981, 'Snacks', 'Food & Beverage'),
(982, 'Beverages', 'Food & Beverage'),
(983, 'Specialty Diet', 'Food & Beverage'),
(984, 'Fresh Produce', 'Food & Beverage'),
(985, 'Dairy & Eggs', 'Food & Beverage'),
(986, 'Meat & Seafood', 'Food & Beverage'),
(987, 'Frozen Foods', 'Food & Beverage'),
(988, 'Baking Supplies', 'Food & Beverage'),
(989, 'Wine & Spirits', 'Food & Beverage'),
(990, 'Travel Accessories', 'Travel'),
(991, 'Luggage', 'Travel'),
(992, 'Camping Gear', 'Travel'),
(993, 'Travel Clothing', 'Travel'),
(994, 'Travel Health', 'Travel'),
(995, 'Gift Cards', 'Gift'),
(996, 'Experiences', 'Gift'),
(997, 'Flowers', 'Gift'),
(998, 'Greeting Cards', 'Gift'),
(999, 'Party Supplies', 'Gift'),
(1000, 'Electronics', 'Technology');
